name: testing
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install redis
        uses: shogo82148/actions-setup-redis@v1

      - name: Install memcached
        uses: niden/actions-memcached@v7

      - name: Install golang latest version
        uses: actions/setup-go@v2

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: go get -v ./...
      
      - name: Run tests
        run: go test -v ./...